### ISSUE TITLE
How do i disable the hover message?

### ISSUE THREAD

**Issue by arnekick** [Ve6om/SimpleCommands#1]

**Comment by Ve6om** [comment]
You will be able to in the new version, I'll upload it in a few.

**Comment by arnekick** [comment]
Ok great looking forward to it. Will it get updated this week?

**Comment by Ve6om** [comment]
Most likely!

**Comment by Ve6om** [comment]
@arnekick The new version has been released, enjoy!

https://ore.spongepowered.org/Ve6om/SimpleCommands/versions/2.2.0

**Comment by arnekick** [comment]
So howSo how do i disable the hover message now?

**Comment by Ve6om** [comment]
Just empty quotes. 

hovermessage=""
